workflows:
  ios-workflow:
    name: iOS workflow
    max_build_duration: 60

    environment:
      groups:
        - appstore

      xcode: latest
      cocoapods: default

      ios_signing:
        distribution_type: app_store
        bundle_identifier: dk.tina.madplanmester

    scripts:
      - name: Detect Capacitor project dir
        script: |
          if [ -f "client/capacitor.config.ts" ] || [ -f "client/capacitor.config.json" ] || [ -f "client/capacitor.config.js" ]; then
            echo "Using client/ as project dir"
            echo "PROJECT_DIR=client" >> $CM_ENV
          else
            echo "Using repo root as project dir"
            echo "PROJECT_DIR=." >> $CM_ENV
          fi

      - name: Install dependencies
        script: |
          cd "$PROJECT_DIR"
          npm ci || npm install

      - name: Build web
        script: |
          cd "$PROJECT_DIR"
          npm run build

      - name: Ensure iOS platform exists + Sync Capacitor
        script: |
          cd "$PROJECT_DIR"
          if [ ! -d "ios" ]; then
            echo "ios/ folder not found -> adding iOS platform"
            npx cap add ios
          fi
          npx cap sync ios

      - name: Set up code signing
        script: |
          cd "$PROJECT_DIR"
          xcode-project use-profiles

      - name: Build iOS IPA
        script: |
          cd "$PROJECT_DIR"

          if [ -d "ios/App/App.xcworkspace" ]; then
            xcode-project build-ipa \
              --workspace ios/App/App.xcworkspace \
              --scheme App \
              --export-method app-store
          else
            xcode-project build-ipa \
              --project ios/App/App.xcodeproj \
              --scheme App \
              --export-method app-store
          fi
