workflows:
  ios-workflow:
    name: ios workflow
    max_build_duration: 60

    environment:
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Build IPA
        script: |
          cd ios/App
          xcode-project build-ipa \
            --workspace App.xcodeproj/project.xcworkspace \
            --scheme App

    artifacts:
      - ios/build/**/*.ipa

