workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build iOS
        script: |
          npx cap sync ios
    artifacts:
      - ios/build/**/*.ipa
