workflows:
  ios-workflow:
    name: iOS workflow
    max_build_duration: 60

    environment:
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          cd client
          npm ci || npm install

      - name: Build web
        script: |
          cd client
          npm run build

      - name: Sync Capacitor (generér ios/App/App.xcworkspace)
        script: |
          cd client
          npx cap sync ios

      - name: Verify workspace exists
        script: |
          ls -la ios/App || true
          ls -la ios/App/App.xcworkspace || true

      - name: Build iOS archive (workspace)
        script: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive
